import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Hero from "@/components/Hero";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SAIGTH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} overflow-x-hidden`}>
        <Hero />
        {children}
      </body>
    </html>
  );
}
